name: quizaja
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.1.0
  animate_do: ^3.3.4
  confetti: ^0.7.0
  device_preview: ^1.1.0
  flutter_animate: ^4.5.0 # Untuk animasi yang lebih beragam
  avatar_glow: ^3.0.1 # Untuk efek glow pada ikon
  audioplayers: ^5.2.1 # Untuk efek suara

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/correct.mp3
    - assets/sounds/wrong.mp3
    - assets/sounds/complete.mp3